### PR TITLE
update energy for current Poke

### PR DESCRIPTION
**Pull request by debopamsengupta**
This is fetching energyGain from the backend as updated in https://github.com/DeveloperKhan/pogo-web-backend/pull/2 
 max energy is 100 :)  

this will also fit in nicely with https://github.com/DeveloperKhan/pogo-web/pull/14

### CODE REVIEW

**Comment by debopamsengupta** [comment]
this also completes #4

**Review by DeveloperKhan — APPROVED** [review]

**Review by DeveloperKhan — CHANGES_REQUESTED** [review]
Instead of adding energy to the Pokemon here on the frontend, could you add the energy in the backend then just send over the Pokemon's current energy? This is to protect against hackers that can easily change frontend values to get infinite charge moves. Also if the frontend disconnects and reconnects, all the energy will be forgotten.

**Comment by jarthur22** [comment]
I think if the frontend disconnects, the battle should be over regardless, that's how Niantic handles it.
Energy on the backend will require more calcs on the server, which will clog up the thread.
So either (1) we move energy to the backend and prepare to take more measures to prevent lag, or (2) we keep energy on the frontend and implement checks and balances to anticipate and prevent hacking changes.

**Comment by debopamsengupta** [comment]
the calculation on the backend is not hard, I just wasn't sure how the current energy of a pokemon is passed to the backend

**Comment by debopamsengupta** [comment]
@DeveloperKhan updated it to be on the backend

**Review by DeveloperKhan — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
